### ISSUE TITLE
Still the old "German"

### ISSUE THREAD

**Issue by jfrcom** [Alheimsins/bigfive-web#170]
Hello,

After deploying it to now again, I still have the old "German" in the test. Do you have any idea how to fix that? 
On my local machine, it's working. I already did a new clone, but when I deploy it at now, there is also the old questions.

**Comment by zrrrzzt** [comment]
The 1.0.1 release features the newest (v2.1.1) of @alheimsins/b5-johnson-120-ipip-neo-pi-r with your updates. To check if this is the version you have deployed to now you can add ```/_src```at the root of your deployment to see the content and then confirm the version from the package.json. If it is the right version maybe something is cached so you'll need a hard refresh.

I've deployed the newest version at [myb5test.now.sh](https://myb5test.now.sh) so you can see if this contains the right version of German.

**Comment by jfrcom** [comment]
Thank's a lot for your quick answer! It's working perfectly fine right now.
