### ISSUE TITLE
now.json for now v2

### ISSUE THREAD

**Issue by jfrcom** [Alheimsins/bigfive-web#198]
hi, 

do you have a now.json with version 2?

**Comment by zrrrzzt** [comment]
Not yet. There will be one available in the foreseeable future though :-)
The release of Next version 8 made it easy to build a serverless version so we will release after some testing.

**Comment by maccyber** [comment]
We started to convert to now v2, use react hooks and some code cleanup in https://github.com/Alheimsins/bigfive-web-serverless-hooks

Not working yet though.

**Comment by jfrcom** [comment]
Any news?

**Comment by maccyber** [comment]
Sorry, no progress.
May be that I get the groove in the summer vacation, but don't get your hopes up.
