### ISSUE TITLE
can't install on glitch+mLab

### ISSUE THREAD

**Issue by j2l** [Alheimsins/bigfive-web#218]
Hi,
Thank you very much, this project is a great idea!

There are errors when trying to install it on glitch.com
I changed localhost to the correct domain name, adapted to use mLab db and had to run `next build` in the console and it ran.
Web page is showing at https://alheimsins-bigfive-web.glitch.me, but example and finalizing the test throw client errors in the console, it's related to the db since the `results` collection is not created.
For `example`: 
{name: "Internal Server Error.", message: "500 - Internal Server Error.", statusCode: 500}
```
SW registered:  
ServiceWorkerRegistration {scope: "https://alheimsins-bigfive-web.glitch.me/", updateViaCache: "imports", active: ServiceWorker, installing: null, navigationPreload: NavigationPreloadManager, …}
active: ServiceWorker {scriptURL: "https://alheimsins-bigfive-web.glitch.me/service-worker.js", state: "activated", onerror: null, onstatechange: null}
installing: null
navigationPreload: NavigationPreloadManager {}
onupdatefound: null
paymentManager: PaymentManager {instruments: PaymentInstruments, userHint: ""}
pushManager: PushManager {}
scope: "https://alheimsins-bigfive-web.glitch.me/"
sync: SyncManager {}
updateViaCache: "imports"
waiting: null
__proto__: ServiceWorkerRegistration
```
You can see more errors if you test it directly at https://alheimsins-bigfive-web.glitch.me
AFAIK, there are no error in the server console though https://glitch.com/edit/#!/alheimsins-bigfive-web
If you can't access the server, tell me your glitch username and I'll grant you write access.

I tried with now.sh but I don't get why it can't see the now.json in my repo at project creation and from the local CLI I get something weird:
```
PS E:\bigfive-web> .\now-win.exe secrets add b5-db-connection "username:password@ds32165.mlab.com:25574/db"
> Error! The secret name "b5-db-connection" already exists for this user
PS E:\bigfive-web> .\now-win.exe
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying E:\bigfive-web under zeitco14
> Error! No secret found by uid or name "b5_db_connection"
> More details: https://err.sh/now-cli/env-no-secret
```
Frankly, glitch is far easier, all I need, I think, is to figure out is the db connection.
Thanks for your help.

**Comment by zrrrzzt** [comment]
Thank you for your interest in this project :-)

Love Glitch but have not had the time to play with it so I'm no expert.
I do know there is an `.env` file there and you'll have to configure it the same way as for this example: https://github.com/Alheimsins/bigfive-web/blob/master/docs/now.md#step-4---configure-your-production-environment. If you haven't done that, please give it a try.

It would be very useful if you had the time to do a write up of what you did to make it work on glitch and submit it as a pr. as well. Would probably be of help for many.

**Comment by j2l** [comment]
@zrrrzzt thanks! Sorry I didn't reply before, gmail is simply sending github notification to spam.
Let's fix it together. Here's my contribution.

Here's a quick tuto about glitch (I can make a PR of it later):

- Register at glitch.com
- From the main github project page, copy the clone URL:
![image](https://user-images.githubusercontent.com/65325/55544272-04c6d480-56cb-11e9-9dcc-511f24c270ad.png)

- On glitch, make a new project by pasting the cloning URL of the github project (it can be any NodeJs project, it's not mandatory to be yours):
![image](https://user-images.githubusercontent.com/65325/55544146-c204fc80-56ca-11e9-871d-14c48db0c543.png)

![image](https://user-images.githubusercontent.com/65325/55544754-080e9000-56cc-11e9-92dd-4e950830923b.png)

- Since this project doesn't have an .env file, create a new file and call it `.env`:
![image](https://user-images.githubusercontent.com/65325/55544414-51aaab00-56cb-11e9-9d5a-166699acbe73.png)
This file is special on glitch, nobody but you can see the variables' content.
For instance, another user can see `JWT_SECRET=` but not the content of the JWT_SECRET variable.
Everything calling `process.env` in the code will call the content of the `.env` file.
If you like risks, you can even don't write the env content and stick with config.js

- To populate the .env file, copy content from `config.js`:
```
JWT_SECRET=
DB_CONNECTION=
DB_COLLECTION=
URL=
```
and add your content.
In this project, the URL refers to your project's name, so first let's run it to get the URL by clicking on `Show`:
![image](https://user-images.githubusercontent.com/65325/55545318-3fca0780-56cd-11e9-83e6-631830082978.png)
In my case the URL is `https://alheimsins-bigfive-web.glitch.me` so the .env url must be `https://alheimsins-bigfive-web.glitch.me:3000` (AFAIK, glitch doesn't allow you for other ports but 3000 and 3001, but they are redirected to 443 (https)).
- I recommend clicking on Tools > Logs to see any server error
- Finalize your `.env` file
- You have a (limited) console by clicking `console` on the Logs view:
![image](https://user-images.githubusercontent.com/65325/55546457-a94b1580-56cf-11e9-8c13-b5b03428f18c.png)

- Enter `next build` in the console for this project (see my post above).
- Click on `Show` (only if `Live` is visible, if not, you have errors or it's not ready yet).
- Bam! You have a running NodeJS server for any github NodeJS project.

Extras:
- If you want to make everything private, click on `Share` and tick the lock pad:
![image](https://user-images.githubusercontent.com/65325/55545652-ef9f7500-56cd-11e9-8d98-49ae7627583d.png)
- If you want to share a private server, you can invite others (see in the Share pop-up).

- The only catch is the server sleeps after 20 minutes of inactivity.
- And since glitch users are sometimes using it to spam/do-other-illegal-stuff, IP's can be black listed by other services.

Hope it helps!

Note: My URL here is, automatically, the name of the github project because I was the first to clone it to glitch. It should generate a new name for you. I can rename my project if the owner wants so, this way you can clone and get your project name. Let me know.

Now, you should have something ... not working, since it throws an internal error, hence my ticket 😸 
Would you please take it for there to help fix it?

**Comment by zrrrzzt** [comment]
thx for the guide. I think @maccyber got to take the first shot at this one :-)

**Comment by maccyber** [comment]
Thanks for a great guide and your interest @j2l.

About **now** try
`now-win.exe secrets add b5_db_connection "username:password@ds32165.mlab.com:25574/db`

With underscore instead of hyphen.

About **glitch**

`.env` file only gets read in dev environments.

Try to paste this directly in `config.js` in the project root.

```js
module.exports = {
  JWT_SECRET: process.env.JWT_SECRET || 'Gibberish, jibberish, jibber-jabber and gobbledygook',
  DB_CONNECTION: process.env.DB_CONNECTION || 'hacktoberfest:hacktoberfest1@ds153659.mlab.com:53659/bigfive',
  DB_COLLECTION: process.env.DB_COLLECTION || 'test',
  URL: process.env.URL || 'https://alheimsins-bigfive-web.glitch.me'
}
```

Then presumably `next build`

Try the database connection easily by navigate to https://alheimsins-bigfive-web.glitch.me/result/58a70606a835c400c8b38e84

And look in the console for errors.

The test-database should contain the `58a70606a835c400c8b38e84` reference.

**Comment by j2l** [comment]
Haaa, "-" vs "_", I didn't see it!
I followed your glitch way and had no server error and the example page working!

So, I tested the same process with my db but `next build` didn't created the `results` collection and running the web server throws the error:
```
Error: timeout of 8000ms exceeded
    at e.exports (showResult.js:1)
    at XMLHttpRequest.m.ontimeout (showResult.js:1)
(anonymous) @ main-aa2e1625697cbd4bcfc1.js:10
58a70606a835c400c8b38e84:1 Failed to load resource: the server responded with a status of 500 ()
The FetchEvent for "https://alheimsins-bigfive-web.glitch.me:3000/api/get/58a70606a835c400c8b38e84" resulted in a network error response: an object that was not a Response was passed to respondWith().
```
So, it's the collection creation that is not working somehow. I guess at the `next build` stage.

I also tried with now-win ("Welcome to now way" :) ) but got a `glitch` (ok, I stop with puns):
```
> Success! Secret b5_db_connection added (zeitco14) [561ms]
PS E:\bigfive-web> .\now-win.exe
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying E:\bigfive-web under zeitco14
> Using project bigfive-web
> Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade
```
Sooo, back to square one.

BTW, I was surprised your credentials are working, I expected an error.
So, I made a copy of the test collection on my mLab account.
And now it's working on glitch.
It's definitely a collection creation issue.

If I make the collection manually it works, so I'm fine.
