### ISSUE TITLE
Get Error While Rinning

### ISSUE THREAD

**Issue by Miladkhoshdel** [Alheimsins/bigfive-web#252]
I get Bellow Error when i try to run application with npm.

OS: CentOS7
node: v6.16.0
npm: v3.10.10

`[root@server bigfive-web]# npm run dev

> bigfive-web@1.0.5 dev /home/miladkhosh/domains/miladkhoshdel.com/public_html/bigfive-web
> node server.js

/home/miladkhosh/domains/miladkhoshdel.com/public_html/bigfive-web/node_modules/next-server/dist/lib/router/router.js:352
    async fetchComponent(route) {
          ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/miladkhosh/domains/miladkhoshdel.com/public_html/bigfive-web/node_modules/next/dist/client/router.js:24:32)

npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bigfive-web@1.0.5 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bigfive-web@1.0.5 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bigfive-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bigfive-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bigfive-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/miladkhosh/domains/miladkhoshdel.com/public_html/bigfive-web/npm-debug.log`

**Comment by maccyber** [comment]
Hi @Miladkhoshdel.

Like the error message says `Make sure you have the latest version of node.js and npm installed.`
You need a node-version >=10.0.0

**Comment by Miladkhoshdel** [comment]
Thank You
