### ISSUE TITLE
MongoDB connection issue

### ISSUE THREAD

**Issue by ubartsch** [Alheimsins/bigfive-web#255]
Hi, 

I am trying to run your website to run a personality test as part of a larger study.

But I have problems running the docker deployed production version of the website. 
Specifically, the write access to MongoDB seems to be the problem. 

Using >  npm run dev everything is working fine, all results are written to the mongodb on localhost:27017

When I run the docker file to run the app inside docker I start having problems connecting to MongoDB.
After running `docker build --tag=bigfive . `
inside my app folder, I get the following error when trying to complete the personality test on localhost:3000 with a remote cluster running mongodb

`/src/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: connection 0 to cluster0-shard-00-00-0oylq.mongodb.net:27017 closed
    at Function.MongoError.create (/src/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/src/node_modules/mongodb-core/lib/connection/connection.js:214:22)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)
Emitted 'error' event at:
    at /src/node_modules/mongojs/lib/database.js:31:16
    at connectCallback (/src/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /src/node_modules/mongodb/lib/mongo_client.js:418:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bigfive-web@1.0.4 start: `NODE_ENV=production node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigfive-web@1.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

here is my config.js:

`module.exports = {
  JWT_SECRET: process.env.JWT_SECRET || 'Gibberish, jibberish, jibber-jabber and gobbledygook',
  DB_CONNECTION: process.env.DB_CONNECTION || '*****:*****@cluster0-shard-00-00-0oylq.mongodb.net:27017',
  DB_COLLECTION: process.env.DB_COLLECTION || 'results',
  URL: process.env.URL || 'http://localhost:3000'
}
`

This same error persists for using a MongoDB on localhost:27017

Any hints on how to fix this would be much appreciated!

**Comment by zrrrzzt** [comment]
To see if there is anything wrong with the application you can try to use this config for the db

`hacktoberfest:hacktoberfest1@ds153659.mlab.com:53659/bigfive`

If that works you'll have to check if your connections string is correct.

**Comment by ubartsch** [comment]
Hi zrrrzzt,

Many thanks, the connection to your mlab db seems to work (can you recent entries?).
I guess that means my mongodb is not correctly configured?

**Comment by ubartsch** [comment]
here is the error using a mongodb cluster:

`/src/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: connection 0 to cluster0-shard-00-00-0oylq.mongodb.net:27017 closed
    at Function.MongoError.create (/src/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/src/node_modules/mongodb-core/lib/connection/connection.js:214:22)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)
Emitted 'error' event at:
    at /src/node_modules/mongojs/lib/database.js:31:16
    at connectCallback (/src/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /src/node_modules/mongodb/lib/mongo_client.js:418:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bigfive-web@1.0.4 start: `NODE_ENV=production node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigfive-web@1.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-26T15_22_27_713Z-debug.log`

**Comment by C9-Neo** [comment]
> Hi,
> 
> I am trying to run your website to run a personality test as part of a larger study.
> 
> But I have problems running the docker deployed production version of the website.
> Specifically, the write access to MongoDB seems to be the problem.
> 
> Using > npm run dev everything is working fine, all results are written to the mongodb on localhost:27017
> 
> When I run the docker file to run the app inside docker I start having problems connecting to MongoDB.
> After running `docker build --tag=bigfive . `
> inside my app folder, I get the following error when trying to complete the personality test on localhost:3000 with a remote cluster running mongodb
> 
> `/src/node_modules/mongodb/lib/mongo_client.js:421 throw err ^ MongoError: connection 0 to cluster0-shard-00-00-0oylq.mongodb.net:27017 closed at Function.MongoError.create (/src/node_modules/mongodb-core/lib/error.js:29:11) at Socket.<anonymous> (/src/node_modules/mongodb-core/lib/connection/connection.js:214:22) at Object.onceWrapper (events.js:277:13) at Socket.emit (events.js:189:13) at TCP._handle.close (net.js:597:12) Emitted 'error' event at: at /src/node_modules/mongojs/lib/database.js:31:16 at connectCallback (/src/node_modules/mongodb/lib/mongo_client.js:527:5) at /src/node_modules/mongodb/lib/mongo_client.js:418:11 at process._tickCallback (internal/process/next_tick.js:61:11) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! bigfive-web@1.0.4 start: `NODE_ENV=production node server.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the bigfive-web@1.0.4 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
> 
> here is my config.js:
> 
> `module.exports = { JWT_SECRET: process.env.JWT_SECRET || 'Gibberish, jibberish, jibber-jabber and gobbledygook', DB_CONNECTION: process.env.DB_CONNECTION || '*****:*****@cluster0-shard-00-00-0oylq.mongodb.net:27017', DB_COLLECTION: process.env.DB_COLLECTION || 'results', URL: process.env.URL || 'http://localhost:3000' } `
> 
> This same error persists for using a MongoDB on localhost:27017
> 
> Any hints on how to fix this would be much appreciated!

Hey are you getting through with this? I am getting several errors trying to connect this to my mLab

**Comment by zrrrzzt** [comment]
> I guess that means my mongodb is not correctly configured?

@ubartsch it could be something as simple as the collection is missing and you have to create it yourself. I think this was one of the issues here https://github.com/Alheimsins/bigfive-web/issues/218

There could be a situation where your provider use another type of connection string.

Which provider do you use? If they offer a free tier I can take a look at it this weekend.
