### ISSUE TITLE
Errors with deployment

### ISSUE THREAD

**Issue by C9-Neo** [Alheimsins/bigfive-web#271]
I am getting several errors when attempting to deploy, errors from "No secret found by uid or name" to "missing script: deploy". I would like assistance, thanks in advance.

**Comment by zrrrzzt** [comment]
I guess the way you are trying to deploy is by following the ZEIT/Now guide?

This version of bigfive-web is only compatible with Now v1 and it seems this version no longer is available for new customers. There will be a port compatible with v2 some time in the future but at the moment we have not had the time to look at it.

You can watch this [issue](https://github.com/Alheimsins/bigfive-web/issues/198) for the progress.

If you are able to help you can do so in this repo https://github.com/Alheimsins/bigfive-web-serverless-hooks

If you need your own deployment immediately you can still use docker and deploy to server of your choice.
