### ISSUE TITLE
npm run deploy errors

### ISSUE THREAD

**Issue by C9-Neo** [Alheimsins/bigfive-web#276]
Once I get to step #6 of the now.md "npm run deploy" I am receiving this message:

> now && now alias

> UPDATE AVAILABLE The latest version of Now CLI is 15.8.5
> Run the `now update` command to update to the latest version
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.8.5
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying ~\bigfive-web under ronaldineo
> Using project bigfive-web
> Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bigfive-web@1.0.5 deploy: `now && now alias`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigfive-web@1.0.5 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ronis\AppData\Roaming\npm-cache\_logs\2019-07-25T13_07_59_015Z-debug.log

Once I run "now update" I receive this error: > "Error! Permission denied to modify file "C:\Users\ronis\AppData\Roaming\npm\node_modules\now\download\dist\now.exe". Please run again with an Administrator Command Prompt."

Even after I run again with an Administrator Command prompt, can anyone provide any assistance? Thanks in advance

**Comment by C9-Neo** [comment]
Error Snippet:
![error](https://user-images.githubusercontent.com/25285272/61878499-1e309e00-aebf-11e9-8fbb-1696b339a485.png)

**Comment by paulogdm** [comment]
Hey, Paulo from ZEIT here.

You can only deploy to Now 1.0 if you have a paid plan with us. Free access to the legacy platform is now restricted to old accounts as we have plans to deprecate it in the future.

**Comment by zrrrzzt** [comment]
Thanks for clearing that up @paulogdm 👍 
I thought we only had access due to being early users of ZEIT/Now. I'll update the README with this requirement.

I hope our version supporting v2 is not to far away. The new features of Next.js 9 makes porting much easier.
