### ISSUE TITLE
Results Collation Bug(s)?

### ISSUE THREAD

**Issue by Model299** [Alheimsins/bigfive-web#288]
Hello,
I was able to install the program version 1.0.6 and host the server on port 3000, using the latest nodejs and npm distribution 12.8.0.

When running the site, clicking on the example report causes the site to crash, the logfile indicates that the dev script couldn't run. This crash also corrupts the npm installation which must be repaired by restoring the ownership of the script files like chown-R user:usergroup

`user@server [~]#  info it worked if it ends with ok
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle bigfive-web@1.0.6~predev: bigfive-web@1.0.6
6 info lifecycle bigfive-web@1.0.6~dev: bigfive-web@1.0.6
7 verbose lifecycle bigfive-web@1.0.6~dev: unsafe-perm in lifecycle true
8 verbose lifecycle bigfive-web@1.0.6~dev: PATH: /home/gqqrfwmy/.nvm/versions/no                                                                                                                                                             de/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/gq                                                                                                                                                             qrfwmy/bigfive-web/node_modules/.bin:/home/gqqrfwmy/.nvm/versions/node/v12.8.0/b                                                                                                                                                             in:/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/bin:/usr/bin:/usr/local/sb                                                                                                                                                             in:/usr/sbin:/opt/cpanel/composer/bin:/home/gqqrfwmy/.local/bin:/home/gqqrfwmy/b                                                                                                                                                             in
9 verbose lifecycle bigfive-web@1.0.6~dev: CWD: /home/gqqrfwmy/bigfive-web
10 silly lifecycle bigfive-web@1.0.6~dev: Args: [ '-c', 'node server.js' ]
11 silly lifecycle bigfive-web@1.0.6~dev: Returned: code: 1  signal: null
12 info lifecycle bigfive-web@1.0.6~dev: Failed to exec dev script
13 verbose stack Error: bigfive-web@1.0.6 dev: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/gqqrfwmy/.nvm/versions/n                                                                                                                                                             ode/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/gqqrfwmy/.nvm/versions/n                                                                                                                                                             ode/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc                                                                                                                                                             ess.js:283:5)
14 verbose pkgid bigfive-web@1.0.6
15 verbose cwd /home/gqqrfwmy/bigfive-web
16 verbose Linux 3.10.0-862.9.1.el7.x86_64
17 verbose argv "/home/gqqrfwmy/.nvm/versions/node/v12.8.0/bin/node" "/home/gqqr                                                                                                                                                             fwmy/.nvm/versions/node/v12.8.0/bin/npm" "run" "dev"
18 verbose node v12.8.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error bigfive-web@1.0.6 dev: `node server.js`
22 error Exit status 1
23 error Failed at the bigfive-web@1.0.6 dev script.
23 error This is probably not a problem with npm. There is likely additional log                                                                                                                                                             ging output above.
24 verbose exit [ 1, true ]
`

In trying to create an example test result I ran the test for the first time. Clicking "get results" in the button on the last page did not execute anything. I then lost the test data by clicking another link. No errors are reported in the log.

Is this a possible database connectivity issue? It was running mongodb-enterprise (shell) version 4.0.11 

Thank you for your input, it's wonderful that this project exists!

**Comment by Model299** [comment]
Hi, Just curious if there was ever a solution found?

       With Gratitude,


S. Corey Hixson
Alliance for Public School Technology Resources
www.apstr.org
http://www.linkedin.com/in/model299
+1-720-335-0451

**Comment by maccyber** [comment]
Hi @Model299 

The project is moved to https://github.com/rubynor/bigfive-web

**Comment by Model299** [comment]
Okay I'll check it out. Thank you!

       With Gratitude,


S. Corey Hixson
Alliance for Public School Technology Resources
www.apstr.org
http://www.linkedin.com/in/model299
+1-720-335-0451
