### ISSUE TITLE
 Languages ​​do not appear

### ISSUE THREAD

**Issue by seumateus007** [Alheimsins/bigfive-web#400]
Hello, could you please help me with this error?

![Captura de tela de 2020-03-24 12-09-01](https://user-images.githubusercontent.com/51541798/77441670-76aa9900-6dc8-11ea-8b16-b3ce7c89b4da.png)
![Captura de tela de 2020-03-24 12-08-46](https://user-images.githubusercontent.com/51541798/77441674-77dbc600-6dc8-11ea-93a0-00c79225c856.png)

**Comment by zrrrzzt** [comment]
Fixed in the v2.0.1 release.

If you are interested in the newest versions please take a look at the newest repo https://github.com/rubynor/bigfive-web
