### ISSUE TITLE
Missing 50-item IPIP

### ISSUE THREAD

**Issue by gregk8288** [Alheimsins/bigfive-web#70]
Hi there, 
I see in this repo there is not mention of the 50-item IPIP. Is that still available or has it been discontinued in this version? PS: thanks for the hard work here. this is a really great resource!

**Comment by zrrrzzt** [comment]
This version of bigfive-web will only support the Johnson 120 IPIP-NEO-PI-R items in the foreseeable future.

We will however probably release the 50-items version as a separate module on npm.

**Comment by maccyber** [comment]
@gregk8288: I added 50-items version module at https://github.com/Alheimsins/b5-50-ipip-neo-pi-r

I only added the english translation, but it is also translated to norwegian and spanish [here](https://github.com/maccyber/micro-bigfive-questions/tree/master/data/50)

Shold be easy (but boring) to port them to the new module. Pull requests are always welcome :smile:

**Comment by zrrrzzt** [comment]
@gregk8288 released to npm as well https://www.npmjs.com/package/@alheimsins/b5-50-ipip-neo-pi-r

**Comment by gregk8288** [comment]
Thanks very much guys. This is awesome!
