### ISSUE TITLE
lighthouse complaints about the viewport size

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#75]
lighthouse raises the following issue on viewport size:

![image](https://user-images.githubusercontent.com/701351/46739516-045ffa80-cca1-11e8-9164-dc8ae0a4c713.png)

The viewport code is located here:
https://github.com/Alheimsins/bigfive-web/blob/master/components/alheimsins/Layout.js#L9

When changing the viewports initial-scale to 1, the mobile view is way of.

**Comment by mariogmz** [comment]
@maccyber taking this one!
