### ISSUE TITLE
lighthouse reports The page does not contain a heading, skip link, or landmark region

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#76]
The page does not contain a heading, skip link, or landmark region

![image](https://user-images.githubusercontent.com/701351/46740020-1d1ce000-cca2-11e8-8ec2-8296a14e0600.png)

**Comment by mariogmz** [comment]
@maccyber taking this one!

**Comment by mariogmz** [comment]
@maccyber seems this is not happening anymore running Lighthouse:
![image](https://user-images.githubusercontent.com/6183307/46766391-79cec980-cca7-11e8-9d80-98998842944c.png)
 
I can solve many of these warnings too if you want.
