### ISSUE TITLE
lighthouse reports Form elements do not have associated labels

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#77]
lighthouse reports Form elements do not have associated labels (in frontpage, /results, /compare).

Use `aria-label`?

![image](https://user-images.githubusercontent.com/701351/46740506-4d18b300-cca3-11e8-9a77-503f7629ad74.png)

**Comment by kyle-hall** [comment]
@maccyber I'd like to try this, if I could.

**Comment by maccyber** [comment]
Awesome @kyle-hall 

Start by:
```
git clone https://github.com/Alheimsins/bigfive-web
cd bigfive-web
npm install
```

Create this file in the root-directory:

**.env**
```
DB_CONNECTION=hacktoberfest:hacktoberfest1@ds153659.mlab.com:53659/bigfive
DB_COLLECTION=test
URL=http://localhost:3000
```
And run `npm run dev`

If you have chrome open http://localhost:3000, use developer tools (Ctrl+Shift+J) and go to "Audits" and run "Run audits" at the bottom of the page.

There you can see the error. Try to get rid of the error by i.e. adding `aria-label` to this line
https://github.com/Alheimsins/bigfive-web/blob/master/components/alheimsins/Select.js#L12
