### ISSUE TITLE
Save identified language in localStorage

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#79]
When accessing the frontpage for the first time language is identified by [request-country](https://www.npmjs.com/package/request-country), so that the user user language automatically will be selected in language select-element, but when user refreshes the page the automatically selection is lost.

See logic in https://github.com/Alheimsins/bigfive-web/blob/master/pages/_app.js#L13 and https://github.com/Alheimsins/bigfive-web/blob/master/pages/index.js#L41

**Comment by GusAV** [comment]
I might be able to help you.

**Comment by GusAV** [comment]
Made the PR, hope it helps

**Comment by maccyber** [comment]
Looks great @GusAV. Thanks!
