### ISSUE TITLE
Port charts to newest version of react-google-charts

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#80]
Port charts to the newest version of [react-google-charts](https://github.com/RakanNimer/react-google-charts)

Start by:
```
git clone https://github.com/Alheimsins/bigfive-web
cd bigfive-web
npm install
```

Create this file in the root-directory:

**.env**
```
DB_CONNECTION=hacktoberfest:hacktoberfest1@ds153659.mlab.com:53659/bigfive
DB_COLLECTION=test
URL=http://localhost:3000
```
And run `npm run dev`

```
npm un --save @alheimsins/react-google-charts
npm i --save react-google-charts
```

Change charts in: https://github.com/Alheimsins/bigfive-web/blob/master/components/Summary.js and https://github.com/Alheimsins/bigfive-web/blob/master/components/SummaryCompare.js

See that it scales on mobile and works.

**Comment by divslingerx** [comment]
I'd like to give this a shot
