### ISSUE TITLE
Add multi language support on the home page (react-intl?)

### ISSUE THREAD

**Issue by maccyber** [Alheimsins/bigfive-web#99]
Add multi language support on the home page

i.e. https://github.com/zeit/next.js/tree/canary/examples/with-react-intl

**Comment by CharlyJazz** [comment]
I can help you!

**Comment by CharlyJazz** [comment]
Check this solution: 
https://github.com/CharlyJazz/React-Theme/tree/master/src/i18n
https://github.com/CharlyJazz/React-Theme/blob/master/src/lib/react-i18n-helper/index.js

**Comment by CharlyJazz** [comment]
Example: https://react-theme-1.herokuapp.com/

**Comment by maccyber** [comment]
Sure, looks good :-)

**Comment by CharlyJazz** [comment]
I take it
